-- DROP ANYTHING PRE-EXISTING
DROP DATABASE IF EXISTS atcm;
DROP ROLE IF EXISTS atcm_user;

-- CREATE DB USER
CREATE ROLE atcm_user WITH createdb LOGIN PASSWORD 'atcm_pwd';

-- CREATE ATCM DB
CREATE DATABASE atcm OWNER atcm_user;